kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: task3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "3"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "3"
    spec:
      containers:
      - name: c1 
        image: local-reg:5000/devconf/c1:latest
        volumeMounts:
        - mountPath: "/pv"
          name: v1
      volumes:
      - name: v1
        hostPath:
          type: Directory
          #path: /home/$user/pv/3
