kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-${user}
  labels:
    type: local
    user: ${user}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/${user}/pv/5
